# Generated by Django 2.2.2 on 2019-06-26 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagereceiver', '0002_auto_20190626_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 8, 53, 22, 726136, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 8, 53, 22, 726162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 8, 53, 22, 745217, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 8, 53, 22, 745239, tzinfo=utc)),
        ),
    ]
