# Generated by Django 2.2.2 on 2019-06-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagereceiver', '0004_auto_20190626_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['created_at']},
        ),
    ]
