# Generated by Django 2.2.3 on 2019-08-11 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagereceiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('known', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagereceiver.Known')),
                ('unknown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagereceiver.Phrase')),
            ],
        ),
    ]
