# Generated by Django 2.2.3 on 2019-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagereceiver', '0001_initial'),
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captcha',
            name='known',
        ),
        migrations.AddField(
            model_name='captcha',
            name='known',
            field=models.ManyToManyField(blank=True, null=True, to='pagereceiver.Known'),
        ),
        migrations.RemoveField(
            model_name='captcha',
            name='unknown',
        ),
        migrations.AddField(
            model_name='captcha',
            name='unknown',
            field=models.ManyToManyField(blank=True, null=True, to='pagereceiver.Phrase'),
        ),
    ]
