# Generated by Django 2.2.3 on 2019-08-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagereceiver', '0001_initial'),
        ('captcha', '0002_auto_20190811_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captcha',
            name='known',
        ),
        migrations.AddField(
            model_name='captcha',
            name='known',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagereceiver.Known'),
        ),
        migrations.RemoveField(
            model_name='captcha',
            name='unknown',
        ),
        migrations.AddField(
            model_name='captcha',
            name='unknown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagereceiver.Phrase'),
        ),
    ]
